### ISSUE TITLE
[FEATURE REQUEST] Built-in Cooldown

### ISSUE THREAD

**Issue by ArtifactyNight** [TrPlugins/TrMenu#131]
for now, i need to use permission to check condition for change icon
if i want to make daily reward, sometimes.. player can get double reward when spam clicking. i know it's can setting click delay
but some menu i want to make spam clicking

### **Information about Built-in Cooldown feature**
• cooldown won't reset when player leave a game or server got restarting (probably should have stored cooldown file)
• new command: **/menu debug cooldown [player]** to check all cooldown which people who have
• new command: **/menu cooldown reset/add/remove [name] [player]** to reset all/add/remove cooldown
• new placeholder: **%trmenu_cooldown_[name]%** to check cooldown time (example output: 10 day(s) 3 hour(s) etc.)
• new placeholder: **%trmenu_cooldown_[name]_y/mo/d/h/m/s%** to another check cooldown time (example output: 750 days etc.)

### Example menu:
```yml
'*':
    update: 20
    display:
      material: <skull:9842dc3b917b1a796c303e15105474a8e315de7982b6ca54feafb5a4d13d4e95>
      name: 'COOLDOWN'
      lore:
        - 'NOT COOLDOWN'
    actions:
      left:
        - 'cooldown: daily1 7d12h30m'
        - 'refresh'
    icons:
      - condition: '"cooldown[daily1]" == "true"'
        display:
          lore:
            - 'COOLDOWNED!'
            - ''
            - 'right-click to remove cooldown'
            - 'press num 1 to reset all cooldown'
        actions:
          right:
            - 'rem-cooldown: daily1'
            - 'refresh'
          number_key_1:
            - 'rem-all-cooldown'
            - 'refresh'
```
