### ISSUE TITLE
[Feature] Save placeholders in cache by setting refresh intervals

### ISSUE THREAD

**Issue by Rubenicos** [TrPlugins/TrMenu#251]
**Type**
Perfomance

**Description**
Option to set refresh intervals to parse placeholders on each menu.

**Usage**
Editing menu configuration adding each placeholder with his respective refresh interval.

**Example**
```yaml
Options:
  # Period in ticks
  Placeholders-Refresh:
    '%vault_eco_top_player_3%': 200
    # Set 0 to no refresh
    '%progress_bar_{trmenu_data_points}%': 0
```

**Additional context**
In case making a button where it requires updating his lore in a short interval of ticks but it has placeholders that don't need to be updated or be updated in a different interval, can be fixed by adding the option to save them in the cache for a certain time while the menu is open, CPU consumption could be optimized while avoiding the repetitive use of PlaceholderAPI with heavy placeholders that use things like MySQL to be parsed.
