### ISSUE TITLE
Commands suggestions

### ISSUE THREAD

**Issue by Tanguygab** [TrPlugins/TrMenu#92]
YEEEEEEEEEEEEEEEEEEEEEETTT another suggestion 😅  😂 
So, today, not the Shapes, Arguments, the commands !
Here's what I would like to see in the plugin =)  :
 - - [ ] Support for a way to open the menu as the player, so all placeholders will be parsed, for the specified player, but displayed to you, could look like in DeluxeMenus and like I've done with shapes, something like that: `/trmenu open <menu> -p:<player>`. And you can combine this with another player name to open the menu for a player, as another player like that: `/trmenu open <menu> <playerThatGetsTheMenu> -p:<playerForPlaceholders>`
 - - [x] Support for Shapes in `/trmenu open` as suggested [here](https://github.com/Arasple/TrMenu/issues/90) 
 - - [x] Support for Arguments in `/trmenu open` as suggested [here](https://github.com/Arasple/TrMenu/issues/91) 
 - - [ ] Support for BungeeCord commands as suggested [here ](https://github.com/Arasple/TrMenu/issues/79)
 - - [x] Fix for the `/trmenu template #` command (apparently Hastebin changed their API or something like that, but maybe it would be better if you could use another site like https://paste.helpch.at/ or else maybe just create a file?)
 - - [ ] Some new action types:
 	 - - [x] Fill this file for the `give-item`/`giveitem` action =) https://github.com/Arasple/TrMenu/blob/v2/src/main/kotlin/me/arasple/mc/trmenu/modules/action/impl/item/ActionGiveItem.kt
	 - - [ ] `next-shape` (go to the next shape in the `Shape:` section)
	 - - [ ] `previous-shape` (go to the previous shape in the `Shape:` section)
 	 - - [ ] `back-shape: [shape]` (go to the shape where you came from. If the player doesn't come from another shape, he will be moved to the defined shape. If it isn't defined, stay on the current shape)
 	 - - [ ] `back-menu: [menu]` (go to the menu where you came from. If the player doesn't come from any menu, he will be moved to the defined menu. If it isn't defined, stay on the current menu)
 - - [ ] More bindings options such as:
```yml
Bindings:
  Events:
    - join
    - first-join
    - offhand
    - sneak-offhand
  Entities:
    - CREEPER
    - BLAZE
    - PLAYER
  Blocks:
    - GRASS
    - DIRT
```
- - [ ] Update actions types and change some in modifiers, it could look like that:
```yml
Click-Types:
  - LEFT-<modifiers>
  - RIGHT-<modifiers>
  - DROP-control
  - ALL-<modifiers>

Click-Types-Modifiers:
  - NORMAL
  - SHIFT
  - DOUBLE
  - MIDDLE
  - CONTROL
```
**Note 1:** everything after the `-` is optionnal. If modifiers aren't specified, all modifiers will be valid  
**Note 2:** you can set multiples types by seperating them with a `,` and multiples modifiers with `&` (modifiers will be all needed, so if I have double and shift, I will need to double shift) example:
  ```yml
  actions:
    left-normal,shift: 'open: menu1'
    right-double&shift,left-double&shift:
      - 'tell: hello'
      - 'tell: idk what to say'
```

I think that the Input Catcher's next :p
